import './components/main-component.js'
import './components/login-component.js'
import './components/title-component.js'
import './components/page-component.js'
import './components/error-component.js'
